### ISSUE TITLE
Current failing tests

### ISSUE THREAD

**Issue by henrikromby** [henrikromby/box#3]
So these are the current integration tests that are failing:

```
features/files.feature:60
features/files.feature:74
features/search.feature:6
features/search.feature:12
features/users.feature:41
```

The files ones are related to old versions of files. I don't know if we have the right permission level to test these, but I'll check it out.

The search ones are probably related to insufficient cleanup between tests.

The users one is related to email aliases. Seems like a bug in the API, will contact Box if necessary.

**Comment by Illizian** [comment]
@henrikromby the old versions of files requires an premium account (https://developers.box.com/docs/#files-view-versions-of-a-file), do you have premium?

**Comment by henrikromby** [comment]
Yeah the folks at Box were kind enough to upgrade me to Enterprise for testing purposes when I had some issues with parts of their API :-)

**Comment by Illizian** [comment]
@henrikromby ah, that's epic! You should open up those conversations again when we hit v1, see if we can get the project on https://developers.box.com/sdks/
